# ============================================================
# Examples(executable)
# ============================================================

# Add executable

# add_executable(
#   Query_app
#   query-main.c
# )
#
# target_link_libraries(
#   Query_app
#   PRIVATE
#   Query_lib
#   project_warnings
#   project_sanitizers
# )


